# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$os$username[@](bold bright-yellow)$hostname $directory $git_branch$character'

[character]
#➜
success_symbol = '[▶](bold bright-green)'
error_symbol = '[✗](bold bright-red)'

[directory]
format = '[$path]($style)'
style = 'bold bright-cyan'
truncation_length = 8
truncation_symbol = '…/'
read_only = " 󰌾"

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold bright-blue)[$hostname](bold bright-white)'
trim_at = '.companyname.com'
disabled = false
ssh_symbol = " "


[username]
style_user = 'bold bright-red'
style_root = 'bold bright-blue'
format = '[$user]($style)'
disabled = false
show_always = true

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'bold bright-purple'

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[os]
format = "[$symbol]($style)"
style  = "bold bright-white"
disabled = false

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
